# Generated by Django 5.2.6 on 2025-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bonus_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Количество списанных бонусов', max_digits=10, verbose_name='Использовано бонусов'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма персональной скидки клиента', max_digits=10, verbose_name='Применённая скидка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Базовая цена услуги без скидок', max_digits=10, null=True, verbose_name='Исходная цена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Фактически оплаченная сумма после скидок и бонусов', max_digits=10, verbose_name='Итоговая сумма'),
        ),
    ]
