# Generated by Django 5.2.6 on 2025-10-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicetype_workinghours_alter_car_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.servicecenter', verbose_name='Автосервис')),
            ],
            options={
                'verbose_name': 'Дашборд администратора',
                'verbose_name_plural': 'Дашборды администраторов',
            },
        ),
    ]
