# Generated by Django 5.2.6 on 2025-10-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admindashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicecenter', verbose_name='Автосервис'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecenter', verbose_name='Автосервис'),
        ),
    ]
