# Generated by Django 5.2.6 on 2025-10-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_service_center_servicetype_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_centers/'),
        ),
    ]
