# Generated by Django 5.2.6 on 2025-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicecenter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='photo',
            field=models.ImageField(blank=True, default='service_centers/default_service_center.jpg', null=True, upload_to='service_centers/'),
        ),
    ]
