# Generated by Django 5.2.6 on 2025-10-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicecenter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание обеда'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало обеда'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='core.servicecenter', verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('service_center', 'day_of_week')},
        ),
    ]
