# Generated by Django 5.2.6 on 2025-10-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workinghours_lunch_end_workinghours_lunch_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
