# Generated by Django 5.2.6 on 2025-11-25 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_car_photo_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина блокировки')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заблокировал')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='core.servicecenter', verbose_name='Автосервис')),
            ],
            options={
                'verbose_name': 'Заблокированный слот',
                'verbose_name_plural': 'Заблокированные слоты',
                'ordering': ['date', 'time'],
                'unique_together': {('service_center', 'date', 'time')},
            },
        ),
    ]
