# Generated by Django 5.2.6 on 2025-11-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blockedtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая сумма с учетом скидок и использованных бонусов', max_digits=10, null=True, verbose_name='Оплаченная сумма'),
        ),
    ]
