# Generated by Django 6.0 on 2025-12-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointment_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_centers/'),
        ),
    ]
