# Generated by Django 5.2.6 on 2025-11-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
