# Generated by Django 5.2.6 on 2025-11-26 16:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_payment_bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Процент от стоимости услуги, возвращаемый бонусами при онлайн оплате', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Процент бонусов за онлайн оплату')),
                ('offline_payment_bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Процент от стоимости услуги, возвращаемый бонусами при оплате в центре', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Процент бонусов за оплату в центре')),
                ('max_bonus_usage_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Максимальный процент стоимости услуги, который можно оплатить бонусами', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Максимальный % оплаты бонусами')),
                ('bronze_threshold', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), help_text='Общая сумма покупок для достижения статуса Бронза', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Порог для статуса Бронза')),
                ('silver_threshold', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Общая сумма покупок для достижения статуса Серебро', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Порог для статуса Серебро')),
                ('gold_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Общая сумма покупок для достижения статуса Золото', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Порог для статуса Золото')),
                ('platinum_threshold', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), help_text='Общая сумма покупок для достижения статуса Платина', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Порог для статуса Платина')),
            ],
            options={
                'verbose_name': 'Настройки программы лояльности',
                'verbose_name_plural': 'Настройки программы лояльности',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='1 бонус = 1 рубль', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Баланс бонусов')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма покупок')),
                ('status', models.CharField(choices=[('NONE', 'Без статуса'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото'), ('PLATINUM', 'Платина')], default='NONE', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт лояльности',
                'verbose_name_plural': 'Аккаунты лояльности',
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Начислено'), ('SPENT', 'Списано'), ('EXPIRED', 'Сгорело')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty_program.loyaltyaccount', verbose_name='Аккаунт лояльности')),
            ],
            options={
                'verbose_name': 'Транзакция бонусов',
                'verbose_name_plural': 'Транзакции бонусов',
                'ordering': ['-created_at'],
            },
        ),
    ]
