# Generated by Django 5.2.6 on 2025-11-26 16:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyaccount',
            name='personal_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Дополнительная скидка для клиента (устанавливается вручную)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Персональная скидка'),
        ),
    ]
