# Generated by Django 5.2.6 on 2025-11-26 17:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_program', '0002_loyaltyaccount_personal_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltysettings',
            name='bronze_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Процент скидки для клиентов со статусом Бронза', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка для Бронзы'),
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='gold_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Процент скидки для клиентов со статусом Золото', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка для Золота'),
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='platinum_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Процент скидки для клиентов со статусом Платина', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка для Платины'),
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='silver_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Процент скидки для клиентов со статусом Серебро', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка для Серебра'),
        ),
    ]
